#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# put the mesh generation here.

# extract mesh times from folder names. 
ls -d constant/meshToMesh_* | sed 's/.*meshToMesh_//' \
    | sort -n > constant/meshTimes

#------------------------------------------------------------------------------
